version: 0.2

phases:
  pre_build:
    commands:
      - aws codeartifact login --tool npm --repository vfs-payments-api --domain vfs --domain-owner 818469940209
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build